spring:
  application:
    name: spring_ai_project

  datasource:
    hikari:
      jdbc-url: jdbc:mysql://123.56.49.39:3306/shf_web?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true&useInformationSchema=true&allowLoadLocalInfile=true&allowLocalInfile=true&allowUrlInLocalInfile=true&allowPublicKeyRetrieval=true&allowPublicKeyRetrieval=true&allowPublicKeyRetrieval=true&allowPublicKeyRetrieval=true&allow
      username: root
      password: ${MYSQL_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver

  ai:
    dashscope:
      api-key: ${DASH_SCOPE_API_KEY}

  memory:
    redis:
      host: 123.56.49.39
      port: 6379
      password: ${REDIS_PASSWORD}
      timeout:  5000
#    openai:
#      # 上述获取的的API-KEY
#      api-key: ${OPENAI_API_KEY}
#      base-url: https://dashscope.aliyuncs.com/compatible-mode
#      chat:
#       options:
#        # 使用的模型
#        model: qwen-flash
#        # 采样的随机性 0~1 较高的值将使输出更具随机性，而较低的值将使结果更加集中和确定
#        temperature: 0.8
#
#logging:
#  level:
#    org.springframework.ai.chat.client.advisor: debug