spring:
  application:
    name: spring_ai_project

  datasource:
    hikari:
      jdbc-url: jdbc:mysql://123.56.49.39:3306/shf_web?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true&useInformationSchema=true&allowLoadLocalInfile=true&allowLocalInfile=true&allowUrlInLocalInfile=true&allowPublicKeyRetrieval=true&allowPublicKeyRetrieval=true&allowPublicKeyRetrieval=true&allowPublicKeyRetrieval=true&allow
      username: root
      password: 160877
      driver-class-name: com.mysql.cj.jdbc.Driver

  ai:
    dashscope:
      api-key: sk-4e9f6fa003234bd89d1b5577f3edaa31

    memory:
      redis:
        host: 123.56.49.39
        port: 6379
        password: Hf960416
        timeout:  5000


quotes:
  api:
    key: 1f055e01054381fa43eb337869e0c0b4

