spring:
  application:
    name: spring_ai_project

  datasource:
      url: jdbc:mysql://123.56.49.39:3306/shf_web
      username: root
      password: 160877
      driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # 可选：create, create-drop, update, validate, none
    show-sql: true       # 开发时方便看 SQL
    properties:
      hibernate.format_sql: true


  ai:
    dashscope:
      api-key: sk-4e9f6fa003234bd89d1b5577f3edaa31

    memory:
      redis:
        host: 123.56.49.39
        port: 6379
        password: Hf960416
        timeout:  5000


quotes:
  api:
    key: 1f055e01054381fa43eb337869e0c0b4

